using System;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;
using System.Collections.Generic;

namespace SteelShapesLibrary
{
      public class ShapeSelectionForm : Form
          {
                  private TextBox _searchBox;
                          private DataGridView _shapesGrid;
                                  private Button _selectButton;
                                          private Button _cancelButton;
                                                  public SteelShape? SelectedShape { get; private set; }

                                                          public ShapeSelectionForm()
                                                                  {
                                                                              this.Text = "AISC Steel Shape Selection";
                                                                                          this.Size = new Size(450, 600);
                                                                                                      this.StartPosition = FormStartPosition.CenterScreen;
                                                                                                                  this.TopMost = true;
                                                                                                                  
                                                                                                                              Label searchLabel = new Label { Text = "Search Shapes (e.g. W12 or L4):", Dock = DockStyle.Top, Height = 25, Font = new Font("Segoe UI", 9, FontStyle.Bold) };
                                                                                                                                          _searchBox = new TextBox { Dock = DockStyle.Top, Height = 30, Font = new Font("Segoe UI", 10) };
                                                                                                                                                      _searchBox.TextChanged += (s, e) => FilterShapes();
                                                                                                                                                      
                                                                                                                                                                  _shapesGrid = new DataGridView
                                                                                                                                                                              {
                                                                                                                                                                                              Dock = DockStyle.Fill,
                                                                                                                                                                                                              SelectionMode = DataGridViewSelectionMode.FullRowSelect,
                                                                                                                                                                                                                              MultiSelect = false,
                                                                                                                                                                                                                                              AllowUserToAddRows = false,
                                                                                                                                                                                                                                                              ReadOnly = true,
                                                                                                                                                                                                                                                                              AutoGenerateColumns = false,
                                                                                                                                                                                                                                                                                              BackgroundColor = Color.White,
                                                                                                                                                                                                                                                                                                              RowHeadersVisible = false
                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                      _shapesGrid.Columns.Add(new DataGridViewTextBoxColumn { HeaderText = "Name", DataPropertyName = "Name", Width = 150 });
                                                                                                                                                                                                                                                                                                                                                  _shapesGrid.Columns.Add(new DataGridViewTextBoxColumn { HeaderText = "Type", DataPropertyName = "Type", Width = 60 });
                                                                                                                                                                                                                                                                                                                                                              _shapesGrid.Columns.Add(new DataGridViewTextBoxColumn { HeaderText = "Depth", DataPropertyName = "Depth", Width = 80 });
                                                                                                                                                                                                                                                                                                                                                                          _shapesGrid.Columns.Add(new DataGridViewTextBoxColumn { HeaderText = "Width", DataPropertyName = "Width", Width = 80 });
                                                                                                                                                                                                                                                                                                                                                                                      _shapesGrid.CellDoubleClick += (s, e) => SelectAndClose();
                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                  Panel btnPanel = new Panel { Dock = DockStyle.Bottom, Height = 50 };
                                                                                                                                                                                                                                                                                                                                                                                                              _cancelButton = new Button { Text = "Cancel", Size = new Size(100, 35), Location = new Point(220, 7) };
                                                                                                                                                                                                                                                                                                                                                                                                                          _cancelButton.Click += (s, e) => this.Close();
                                                                                                                                                                                                                                                                                                                                                                                                                                      _selectButton = new Button { Text = "Select Shape", Size = new Size(100, 35), Location = new Point(325, 7), BackColor = Color.FromArgb(0, 122, 204), ForeColor = Color.White, Font = new Font("Segoe UI", 9, FontStyle.Bold) };
                                                                                                                                                                                                                                                                                                                                                                                                                                                  _selectButton.Click += (s, e) => SelectAndClose();
                                                                                                                                                                                                                                                                                                                                                                                                                                                              btnPanel.Controls.AddRange(new Control[] { _cancelButton, _selectButton });
                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          this.Controls.AddRange(new Control[] { _shapesGrid, _searchBox, searchLabel, btnPanel });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  _shapesGrid.DataSource = AiscDatabase.AllShapes;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              this.ActiveControl = _searchBox;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              private void FilterShapes()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  string filter = _searchBox.Text.ToLower();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (string.IsNullOrWhiteSpace(filter))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          _shapesGrid.DataSource = AiscDatabase.AllShapes;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  else
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              _shapesGrid.DataSource = AiscDatabase.AllShapes
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .Where(s => s.Name.ToLower().Contains(filter) || s.Type.ToLower().Contains(filter))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .ToList();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  private void SelectAndClose()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (_shapesGrid.SelectedRows.Count > 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  SelectedShape = _shapesGrid.SelectedRows[0].DataBoundItem as SteelShape;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  this.DialogResult = DialogResult.OK;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  this.Close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          else
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      MessageBox.Show("Please select a shape from the list first.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
